config/routes.rb
Tunr::Application.routes.draw do
    resources :artists do
      resources :songs
    end

    resources :users
    get "/sessions", to: "sessions#new"
    post "/sessions", to: "sessions#create"
    delete "/sessions", to: "sessions#destroy"

    root "welcome#index"
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs, dependent: :destroy
  belongs_to :user
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :dob, presence: true
  self.has_secure_password()
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  self.before_action :load_artists, only: [:show, :edit, :update, :destroy]

  def index
    @artist = Artist.all
    render(:index)
  end

  def show
    render(:show)
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(artist_params)
    redirect_to("/artists/#{@artist.id}/songs")
  end

  def edit
    render(:edit)
  end

  def update
    @artist.update(artist_params)
    redirect_to("/artists/#{@artist.id}/songs")  
  end

  def destroy
    @artist.destroy
    redirect_to("/artists")
  end


  private

  def load_artists
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :genre, :photo_url)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
  end

  def new
  end

  def create
    # authenticate: check whether this info matches what's in the database
    # and if so go to the user page, if not ... Self destruct!

    #find if any user has that email
    user = User.find_by(email: params[:email])

    #if that user exists and has a password that was sent
    if user && (user.authenticate(params[:password]) )

    #save the user_id in the session hash and redirect to the user's homepage
      session[:user_id] = user.id
      redirect_to (user_path(user) )

    else
      @message = "User Not Found or Wrong Password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  self.before_action :load_artist
  self.before_action :load_song, only: [:edit, :update, :destroy]

  def index
    @songs = @artist.songs.all
    render(:index)
  end

  def show
    @songs = @artist.songs.find(params[:id])
    render(:show)
  end

  def new
    @song = Song.new
  end

  def create
    @song = @artist.songs.create(song_params)
    @song.preview_url = get_preview_url(@artist.name, @song.title)
    @song.save

    redirect_to artist_path(@artist)
  end

  def edit
    render(:edit)
  end

  def update
    @song.update(song_params)  
    redirect_to artist_path(@artist)
  end

  def destroy
    @song.destroy
    redirect_to("/artists/#{@artist.id}/songs")
  end

  private

  def load_artist
    return @artist = Artist.find(params[:artist_id])
  end

  def load_song
    return @song = @artist.songs.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:title, :year)
  end

  def get_preview_url(artist, song)
    artist = artist.gsub(" ", "+")
    song = song.gsub(" ", "+")
    from_itunes = HTTParty.get("http://itunes.apple.com/search?term=#{artist}+#{song}&media=music&entity=musicTrack&limit=1")
    from_itunes_as_hash = JSON(from_itunes)
    return from_itunes_as_hash["results"][0]["previewUrl"]
  end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :load_user, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new     
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    render :show
  end

  def edit
    render :edit
  end

  def update
    @update = @user.update(user_params)

    if @update
      redirect_to("/users/#{@user.id}")
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to("/")
  end

  private
    def load_user
      return @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :dob, :gender, :facebook_link, :password, :password_confirmation)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/edit.html.erb
<h1> Edit an Artist </h1>

<%= form_for @artist do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br />
<%= f.label :genre %>
<%= f.text_field :genre %><br />
<%= f.label :photo_url %>
<%= f.url_field :photo_url %><br />
<%= f.submit %>
<% end %>

app/views/artists/index.html.erb
<h1> List of Artists </h1>
<button><a href="/artists/new">Add Artist</a></button>
<ul>
  <% @artist.each do |artist| %>
    <li><img src="<%= artist.photo_url %>" /></li>

    <li><a href="/artists/<%=artist.id%>/songs"><%= artist.name %></a></li>

    <%= link_to "Edit Artist", {controller: "artists",action: "edit", id: "#{artist.id}"}%>

    <%= button_to "Delete Artist", { action: "destroy", id: artist.id}, method: :delete, data: { confirm: "Are you sure?"} %><br />

  <% end %>
</ul>

app/views/artists/new.html.erb
<h1> Add New Artist </h1>

<%= form_for @artist do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br />
<%= f.label :genre %>
<%= f.text_field :genre %><br />
<%= f.label :photo_url %>
<%= f.url_field :photo_url %><br />
<%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1>Info for <%=@artist.name %></h1>

<p>Genre: <%= @artist.genre %></p>
<img src="<%= @artist.photo_url %>" />
<br></br>
<button><a href="/artists/<%= @artist.id %>/songs">Songs</a></button>
<button><a href="/artists">Main Page</a></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tunr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
<%= link_to "Home", root_path %>
<%= link_to "Please Log in!", sessions_path if session[:user_id].nil? %>
<%= link_to("Log Out #{User.find_by(id: session[:user_id]).first_name}!", "/sessions", method: "delete") unless session[:user_id].nil? %>

</header>
<%= yield %>

</body>
</html>

app/views/songs/edit.html.erb
<h1> Edit Song </h1>

<%= form_for [@artist, @song] do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :year %>
<%= f.number_field :year %>
<%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<h1> Songs by <%= @artist.name %> </h1>
<button><a href="songs/new">Add New Song</a></button>
<br></br>
<img src="<%= @artist.photo_url %>" />
<p>Genre: <%= @artist.genre %></p>
<ul>
  <% @songs.each do |song| %>
    <li><%= song.title %>: <%= song.year %></li>
      <audio controls>
        <source src="<%= song.preview_url %>">
      </audio>
      <br />

    <%= link_to "Edit Song", {controller: "songs",action: "edit", id: "#{song.id}"}%>
    <%= button_to "Delete Song", { action: "destroy", id: song.id}, method: :delete, data: { confirm: "Are you sure?"} %><br />
  <% end %>
</ul>
<button><a href="/artists">Main Page</a></button>

app/views/songs/new.html.erb
<h1> Add New Song </h1>

<%= form_for [@artist, @song] do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :year %>
<%= f.number_field :year %>
<%= f.submit %>
<% end %>

app/views/songs/show.html.erb
<h3> Info for <%= @songs.title %> by <%= @artist.name %></h3>

<p>Year: <%= @songs.year %></p>

app/views/users/edit.html.erb
<h1> Edit User Info </h1>

<% if @update == false %>
  <div id="errors">
    <h3> Errors!! </h3>
    <ul>

      <% @user.errors.messages.each do |field, error| %>
      <li><%= "#{field.capitalize}: #{error.first}" %></li>
      <% end %>

    </ul>
  </div>
<% end %>

<%= form_for @user, url: {action: "update"} do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name %>
<%= f.label :last_name %>
<%= f.text_field :last_name %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :birthdate %>
<%= f.date_field :dob %>
<%= f.label :gender %>
<%= f.text_field :gender %>
<%= f.label :facebook_link %>
<%= f.url_field :facebook_link %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1> Sign Up for Tun<span>R</span>! </h1>

<% unless @user.errors.messages.empty? %>
  <div id="errors">
    <h3> Errors!! </h3>
    <ul>

      <% @user.errors.messages.each do |field, error| %>
      <li><%= "#{field.capitalize}: #{error.first}" %></li>
      <% end %>

    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name %><br />
<%= f.label :last_name %>
<%= f.text_field :last_name %><br />
<%= f.label :email %>
<%= f.text_field :email %><br />
<%= f.label :birthdate %>
<%= f.date_field :dob %><br />
<%= f.label :gender %>
<%= f.text_field :gender %><br />
<%= f.label :facebook_link %>
<%= f.url_field :facebook_link %><br />
<%= f.label :password %>
<%= f.password_field :password %><br />
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %><br />
<%= f.submit "create" %>
<% end %>

app/views/users/show.html.erb
<h1> Info for <%= @user.first_name %> <%= @user.last_name %></h1>

<p>Email: <%= @user.email %> </p>
<p>Date of Birth: <%= @user.dob %> </p>
<p>Gender: <%= @user.gender %> </p>
<p>Facebook Page: <%= @user.facebook_link %> </p>



<%=link_to "Update Info", {controller: "users",action: "edit", id: "#{@user.id}"}%>

<%= button_to "Delete Account", { action: "destroy", id: @user.id}, method: :delete, html: "del", data: { confirm: "Are you sure?"} %>

app/views/welcome/index.html.erb
<div class='titles'>
<h1> Welcome to Tun<span>R</span>! </h1>
</div>
<div class="mainbox">
<button><%=link_to "Join Us!", controller: "users", action: "new"%></button>
<button><%=link_to "Login", sessions_path %></button>
<br></br>
<img src="http://coolmaterial.com/wp-content/uploads/2008/10/boombox-gelaskin.jpg" />

<p><%= link_to "Browse Artists", artists_path %></p>
</div>